notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

env:
 - CC=gcc

addons:
 apt:
  packages:
   - build-essential
   - curl
   - libcurl4-openssl-dev
   - nettle-dev
   - zlib1g-dev

install: true

script:
 - ./setup.sh ~/wtsi-opt