notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

sudo: false

services:
  - docker

script:
 - set -e
 - echo 'Build and check docker image'
 - docker build -t cgpbigwig .
 - docker images | grep -c cgpbigwig
 - echo 'Verify program(s) from this repo'
 - docker run -t --rm cgpbigwig bam2bedgraph --version
 - docker run -t --rm cgpbigwig bwjoin --version
 - docker run -t --rm cgpbigwig bam2bw --version
 - docker run -t --rm cgpbigwig bwcat --version
 - docker run -t --rm cgpbigwig bam2bwbases --version
 - docker run -t --rm cgpbigwig bg2bw --version
 - docker run -t --rm cgpbigwig detectExtremeDepth --version
